[package]
name = "amethystate-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Internal crate for amethystate, not intended for direct use"
keywords.workspace = true
categories.workspace = true
readme.workspace = true
rust-version.workspace = true

[dependencies]
arc-swap.workspace = true
dashmap.workspace = true
error-stack.workspace = true
parking_lot.workspace = true
rpds.workspace = true
smol_str.workspace = true
serde.workspace = true
tracing.workspace = true
inventory.workspace = true

futures = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
async-trait = { workspace = true, optional = true }
uuid = { workspace = true, features = ["v4"] }
thiserror.workspace = true
proptest = { workspace = true, optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
uuid = { workspace = true, features = [ "v4", "js", "serde"] }

[features]
test-utils = []
proptest-strategies = ["dep:proptest"]
async = ["dep:futures", "dep:serde_json", "dep:async-trait"]

[dev-dependencies]
proptest.workspace = true
