[package]
name = "tauri-leptos-ui"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
amethystate = { path = "../../crates/main/amethystate", features = ["tauri"] }
amethystate-arena = { path = "../../crates/main/amethystate-arena" }
amethystate-leptos = { path = "../../crates/adapters/amethystate-leptos" }
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
leptos = { version = "0.8", features = ["csr"] }
log = "0.4"
shared = { path = "./shared" }

[workspace]
members = ["shared", "src-tauri"]
