[default]
description = "Allows access to the default amethystate commands"
permissions = [
    "allow-amethystate-get",
    "allow-amethystate-set",
    "allow-amethystate-delete",
    "allow-amethystate-delete-prefix",
    "allow-amethystate-scan-keys",
    "allow-amethystate-subscribe",
    "allow-amethystate-unsubscribe",
    "allow-amethystate-get-prefix",
    "allow-amethystate-flush"
]