// Generated by amethystate-codegen from the Rust declarations. Do not edit.
import { Field, Loaded, ReactiveMap, Slice, tauri, type Transport } from "amethystate";
import type { Todo } from "./Todo";
import type { TodoList } from "./TodoList";

export class Todos extends Slice {
    readonly nextId: Field<number>;
    readonly hideDone: Field<boolean>;
    readonly lists: ReactiveMap<TodoList>;
    readonly items: ReactiveMap<Todo>;

    private constructor(loaded: Loaded) {
        super(loaded);
        this.nextId = loaded.field(["todos", "next_id"]);
        this.hideDone = loaded.field(["todos", "hide_done"]);
        this.lists = loaded.map(["todos", "lists"]);
        this.items = loaded.map(["todos", "items"]);
    }

    static async load(transport: Transport = tauri()): Promise<Todos> {
        return new Todos(await Loaded.under(transport, ["todos"]));
    }
}

