[package]
name = "amethystate-example-web-dioxus"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
amethystate = { path = "../../crates/main/amethystate", features = ["localstorage"] }
amethystate-arena = { path = "../../crates/main/amethystate-arena" }
amethystate-dioxus = { path = "../../crates/adapters/amethystate-dioxus", default-features = false }
dioxus = { version = "0.7.9", default-features = false, features = ["web", "launch", "logger", "macro", "html", "signals", "hooks"] }
serde = { version = "1.0", features = ["derive"] }
