mod backends;
pub use backends::*;

use amethystate_core::{FieldKind, SchemaExportEntry};
use heck::ToLowerCamelCase;
use std::collections::BTreeMap;
use std::io;
use std::path::Path;

pub trait FrameworkCodegen {
    fn imports(&self) -> &str {
        ""
    }
    fn extra_derives(&self) -> &[&str] {
        &[]
    }
    fn extra_attrs(&self) -> &[&str] {
        &[]
    }
}

pub struct CodegenRegistry {
    registry: BTreeMap<&'static str, &'static SchemaExportEntry>,
}

impl Default for CodegenRegistry {
    fn default() -> Self {
        Self::new()
    }
}

impl CodegenRegistry {
    pub fn new() -> Self {
        let mut registry = BTreeMap::new();
        for entry in amethystate_core::exports() {
            registry.insert(entry.struct_name, *entry);
        }
        Self { registry }
    }

    /// Writes the TypeScript bindings: a class per struct over the `amethystate` npm package.
    ///
    /// A value type that is neither a TypeScript builtin nor a struct declared here is imported
    /// from a file of its own name beside `out_path`, where `ts-rs` writes it.
    pub fn export_ts(&self, out_path: impl AsRef<Path>) -> io::Result<()> {
        let mut used = TsUsed::default();
        let mut nested = String::new();
        let mut roots = String::new();

        for entry in self.registry.values() {
            match entry.prefix {
                None => nested.push_str(&self.ts_node(entry, &mut used)),
                Some(prefix) => roots.push_str(&self.ts_slice(entry, prefix, &mut used)),
            }
        }

        let mut ts = String::from(
            "// Generated by amethystate-codegen from the Rust declarations. Do not edit.\n",
        );
        ts.push_str(&used.package_import());
        for name in &used.types {
            ts.push_str(&format!("import type {{ {name} }} from \"./{name}\";\n"));
        }
        ts.push('\n');
        ts.push_str(&nested);
        ts.push_str(&roots);

        if let Some(parent) = out_path.as_ref().parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(out_path, ts)?;
        Ok(())
    }

    fn ts_node(&self, entry: &SchemaExportEntry, used: &mut TsUsed) -> String {
        used.path = true;
        let mut ts = format!("export class {} {{\n", entry.struct_name);
        ts.push_str(&self.ts_members(entry, used));
        ts.push_str("\n    constructor(loaded: Loaded, at: Path) {\n");
        ts.push_str(&self.ts_builds(entry, "...at", used));
        ts.push_str("    }\n}\n\n");
        ts
    }

    fn ts_slice(&self, entry: &SchemaExportEntry, prefix: &str, used: &mut TsUsed) -> String {
        used.slice = true;
        let items = ts_items(&levels_of(prefix));
        let at = format!("[{items}]");
        let name = entry.struct_name;

        let mut ts = format!("export class {name} extends Slice {{\n");
        ts.push_str(&self.ts_members(entry, used));
        ts.push_str("\n    private constructor(loaded: Loaded) {\n        super(loaded);\n");
        ts.push_str(&self.ts_builds(entry, &items, used));
        ts.push_str("    }\n\n");
        ts.push_str(&format!(
            "    static async load(transport: Transport = tauri()): Promise<{name}> {{\n        return new {name}(await Loaded.under(transport, {at}));\n    }}\n}}\n\n"
        ));
        ts
    }

    fn ts_members(&self, entry: &SchemaExportEntry, used: &mut TsUsed) -> String {
        let mut ts = String::new();
        for field in entry.fields {
            let member = match &field.kind {
                FieldKind::Plain => {
                    used.field = true;
                    self.ts_note_types(field.full_ts_type, used);
                    format!("Field<{}>", field.full_ts_type)
                }
                FieldKind::Nested { struct_name } => struct_name.to_string(),
                FieldKind::ReactiveMap { value_type, .. } => {
                    used.map = true;
                    self.ts_note_types(value_type, used);
                    format!("ReactiveMap<{value_type}>")
                }
                FieldKind::Volatile => continue,
            };
            ts.push_str(&format!(
                "    readonly {}: {member};\n",
                field.name.to_lower_camel_case()
            ));
        }
        ts
    }

    fn ts_builds(&self, entry: &SchemaExportEntry, at: &str, used: &mut TsUsed) -> String {
        let mut ts = String::new();
        for field in entry.fields {
            let path = ts_path(at, field.stored);
            let built = match &field.kind {
                FieldKind::Plain => format!("loaded.field({path})"),
                FieldKind::ReactiveMap { .. } => format!("loaded.map({path})"),
                FieldKind::Nested { struct_name } => {
                    used.path = true;
                    format!("new {struct_name}(loaded, {path})")
                }
                FieldKind::Volatile => continue,
            };
            ts.push_str(&format!(
                "        this.{} = {built};\n",
                field.name.to_lower_camel_case()
            ));
        }
        ts
    }

    fn ts_note_types(&self, ts_type: &str, used: &mut TsUsed) {
        for name in ts_type.split(|ch: char| !(ch.is_alphanumeric() || ch == '_' || ch == '$')) {
            let starts_like_a_name = name.starts_with(|ch: char| ch.is_alphabetic() || ch == '_');
            if starts_like_a_name
                && !TS_BUILTINS.contains(&name)
                && !self.registry.contains_key(name)
            {
                used.types.insert(name.to_string());
            }
        }
    }
}

const TS_BUILTINS: &[&str] = &[
    "string",
    "number",
    "boolean",
    "bigint",
    "null",
    "undefined",
    "unknown",
    "any",
    "never",
    "Record",
    "Array",
];

#[derive(Default)]
struct TsUsed {
    field: bool,
    map: bool,
    slice: bool,
    path: bool,
    types: std::collections::BTreeSet<String>,
}

impl TsUsed {
    fn package_import(&self) -> String {
        let mut names = Vec::new();
        if self.field {
            names.push("Field");
        }
        if self.slice || self.path {
            names.push("Loaded");
        }
        if self.map {
            names.push("ReactiveMap");
        }
        if self.slice {
            names.extend(["Slice", "tauri"]);
        }
        if self.path {
            names.push("type Path");
        }
        if self.slice {
            names.push("type Transport");
        }
        format!("import {{ {} }} from \"amethystate\";\n", names.join(", "))
    }
}

fn levels_of(dotted: &str) -> Vec<&str> {
    match dotted {
        "" | "." => Vec::new(),
        dotted => dotted.split('.').collect(),
    }
}

fn ts_string(level: &str) -> String {
    format!("\"{}\"", level.replace('\\', "\\\\").replace('"', "\\\""))
}

fn ts_items(levels: &[&str]) -> String {
    let spelled: Vec<String> = levels.iter().map(|level| ts_string(level)).collect();
    spelled.join(", ")
}

fn ts_path(at: &str, stored: &str) -> String {
    let own = ts_items(&levels_of(stored));
    let items: Vec<&str> = [at, own.as_str()]
        .into_iter()
        .filter(|part| !part.is_empty())
        .collect();
    format!("[{}]", items.join(", "))
}

impl CodegenRegistry {
    pub fn export_rust(
        &self,
        out_path: impl AsRef<Path>,
        fw: &dyn FrameworkCodegen,
    ) -> io::Result<()> {
        let mut code = String::new();
        code.push_str("// GENERATED AUTOMATICALLY. DO NOT EDIT.\n");
        code.push_str(fw.imports());
        code.push('\n');

        for entry in self.registry.values() {
            for attr in fw.extra_attrs() {
                code.push_str(&format!("{}\n", attr));
            }

            if let Some(prefix) = entry.prefix {
                code.push_str(&format!(
                    "#[::amethystate::amethystate(prefix = \"{}\", target = \"tauri-wasm\")]\n",
                    prefix
                ));
            } else {
                code.push_str("#[::amethystate::amethystate(target = \"tauri-wasm\")]\n");
            }

            for derive in fw.extra_derives() {
                code.push_str(&format!("#[derive({})]\n", derive));
            }

            code.push_str(&format!("pub struct {} {{\n", entry.struct_name));

            for field in entry.fields {
                let mut attributes = Vec::new();
                match &field.kind {
                    FieldKind::Volatile => attributes.push("volatile".to_string()),
                    FieldKind::Nested { .. } => attributes.push("nested".to_string()),
                    _ => {}
                }
                match (&field.kind, field.stored) {
                    (FieldKind::Volatile, _) => {}
                    (FieldKind::Nested { .. }, "") => attributes.push("flatten".to_string()),
                    (_, stored) if stored != field.name => {
                        attributes.push(format!("path = \"{stored}\""))
                    }
                    _ => {}
                }

                if !attributes.is_empty() {
                    code.push_str(&format!("    #[amestate({})]\n", attributes.join(", ")));
                }

                code.push_str(&format!("    pub {}: {},\n", field.name, field.rust_type));
            }
            code.push_str("}\n\n");
        }

        if let Some(parent) = out_path.as_ref().parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(out_path, code)?;
        Ok(())
    }
}

#[doc = include_str!("../README.md")]
#[macro_export]
macro_rules! amethystate_codegen {
    (rs_out = $rs_out:expr, framework = $fw:ident) => {
        $crate::amethystate_codegen!(@run $rs_out, $fw, None::<&str>)
    };
    (rs_out = $rs_out:expr, framework = $fw:ident, ts_out = $ts_out:expr) => {
        $crate::amethystate_codegen!(@run $rs_out, $fw, Some($ts_out))
    };
    (ts_out = $ts_out:expr) => {
        $crate::amethystate_codegen!(@run_ts $ts_out)
    };

    (@run $rs_out:expr, $fw:ident, $ts_opt:expr) => {
        $crate::amethystate_codegen!(@exec $rs_out, $fw, $ts_opt)
    };

    (@run_ts $ts_out:expr) => {
        {
            let reg = $crate::CodegenRegistry::new();
            reg.export_ts($ts_out).expect("TS codegen failed");
        }
    };

    (@exec $rs_out:expr, dioxus, $ts_opt:expr) => {
        {
            let reg = $crate::CodegenRegistry::new();
            reg.export_rust($rs_out, &$crate::TauriDioxusCodegen).expect("Rust codegen failed");
            if let Some(ts) = $ts_opt {
                reg.export_ts(ts).expect("TS codegen failed");
            }
        }
    };

    (@exec $rs_out:expr, yew, $ts_opt:expr) => {
        {
            let reg = $crate::CodegenRegistry::new();
            reg.export_rust($rs_out, &$crate::TauriYewCodegen).expect("Rust codegen failed");
            if let Some(ts) = $ts_opt {
                reg.export_ts(ts).expect("TS codegen failed");
            }
        }
    };

    (@exec $rs_out:expr, leptos, $ts_opt:expr) => {
        {
            let reg = $crate::CodegenRegistry::new();
            reg.export_rust($rs_out, &$crate::TauriLeptosCodegen).expect("Rust codegen failed");
            if let Some(ts) = $ts_opt {
                reg.export_ts(ts).expect("TS codegen failed");
            }
        }
    };

    (@exec $rs_out:expr, vanilla, $ts_opt:expr) => {
        {
            let reg = $crate::CodegenRegistry::new();
            reg.export_rust($rs_out, &$crate::TauriVanillaCodegen).expect("Rust codegen failed");
            if let Some(ts) = $ts_opt {
                reg.export_ts(ts).expect("TS codegen failed");
            }
        }
    };
}

#[doc = include_str!("../README.md")]
#[macro_export]
macro_rules! amethystate_codegen_main {
    (rs_out = $rs_out:expr, framework = $fw:ident) => {
        fn main() {
            $crate::amethystate_codegen!(rs_out = $rs_out, framework = $fw);
        }
    };
    (ts_out = $ts_out:expr) => {
        fn main() {
            $crate::amethystate_codegen!(ts_out = $ts_out);
        }
    };
    (rs_out = $rs_out:expr, framework = $fw:ident, ts_out = $ts_out:expr) => {
        fn main() {
            $crate::amethystate_codegen!(rs_out = $rs_out, framework = $fw, ts_out = $ts_out);
        }
    };
}
