[package]
name = "amethystate-codegen"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
rust-version.workspace = true

[features]
dioxus = []
leptos = []
yew = []

[dependencies]
amethystate-core = { workspace = true }
heck.workspace = true
inventory = { workspace = true }

[dev-dependencies]
amethystate = { workspace = true, features = ["tauri"] }
insta.workspace = true
serde.workspace = true