use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode};

use serde_json::Value;

const PROBES: &str = "crates/main/amethystate/tests";
const SECTION: &str = "landing/src/content/docs/Limitations";
const INDEX: &str = "index.md";

/// What a page may say it is about. Closed on purpose: search is by word, so a
/// page tagged `TOML` and a page tagged `toml` are two vocabularies and neither
/// finds the other. Adding a tag is editing this list, which is the point at
/// which someone decides whether it is a new subject or an existing one spelled
/// differently.
const TAGS: &[&str] = &[
    "atomicity",
    "choosing an engine",
    "codec",
    "depth",
    "json",
    "keys",
    "migration",
    "option",
    "paths",
    "redb",
    "ron",
    "schema",
    "sqlite",
    "toml",
];

fn main() -> ExitCode {
    let check = std::env::args().any(|arg| arg == "--check");

    if std::env::args().any(|arg| arg == "book") {
        return book();
    }

    let probes = probe_files(Path::new(PROBES));
    if probes.is_empty() {
        eprintln!("no tests under {PROBES} - run this from the workspace root");
        return ExitCode::FAILURE;
    }

    let mut pages: BTreeMap<PathBuf, String> = BTreeMap::new();
    let mut unknown: Vec<String> = Vec::new();

    for probe in &probes {
        let Ok(source) = fs::read_to_string(probe) else {
            continue;
        };
        let acts = acts(&source);
        if acts.is_empty() {
            continue;
        }

        let preamble = preamble(&source);
        for tag in tags(&preamble) {
            if !TAGS.contains(&tag.as_str()) {
                unknown.push(format!("{}: {tag}", probe.display()));
            }
        }

        let stem = probe
            .file_stem()
            .and_then(|stem| stem.to_str())
            .unwrap_or_default();
        let features = features(&preamble);

        eprintln!("running {stem}");
        let shown = shown(&source);
        let printed = match output(stem, &features, &shown) {
            Ok(printed) => printed,
            Err(why) => {
                eprintln!("{}: {why}", probe.display());
                return ExitCode::FAILURE;
            }
        };

        let name = title(probe);
        let at = Path::new(SECTION).join(format!("{}.md", name.replace(' ', "-")));
        pages.insert(at, render(&name, &preamble, &acts, &printed));
    }

    if !unknown.is_empty() {
        eprintln!("tags outside the vocabulary in xtask's TAGS:");
        for at in &unknown {
            eprintln!("  {at}");
        }
        eprintln!("\nthe vocabulary is:");
        for tag in TAGS {
            eprintln!("  {tag}");
        }
        eprintln!("\nadd it there if it is a new subject, spell it as above if it is not");
        return ExitCode::FAILURE;
    }

    let stale = stale_pages(Path::new(SECTION), &pages);
    let mut behind: Vec<String> = Vec::new();

    for (at, page) in &pages {
        if fs::read_to_string(at).unwrap_or_default() != *page {
            behind.push(at.display().to_string());
        }
    }
    for at in &stale {
        behind.push(format!("{} (no probe writes it)", at.display()));
    }

    if behind.is_empty() {
        println!("{SECTION} is up to date");
        return ExitCode::SUCCESS;
    }

    if check {
        eprintln!("out of date, run `cargo xtask docs`:");
        for at in &behind {
            eprintln!("  {at}");
        }
        return ExitCode::FAILURE;
    }

    if let Err(e) = fs::create_dir_all(SECTION) {
        eprintln!("cannot make {SECTION}: {e}");
        return ExitCode::FAILURE;
    }
    for (at, page) in &pages {
        if let Err(e) = fs::write(at, page) {
            eprintln!("cannot write {}: {e}", at.display());
            return ExitCode::FAILURE;
        }
    }
    for at in &stale {
        let _ = fs::remove_file(at);
    }

    println!("wrote {} page(s) under {SECTION}", pages.len());
    ExitCode::SUCCESS
}

fn probe_files(at: &Path) -> Vec<PathBuf> {
    let Ok(entries) = fs::read_dir(at) else {
        return Vec::new();
    };

    let mut found: Vec<PathBuf> = entries
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "rs"))
        .collect();

    found.sort();
    found
}

fn render(name: &str, preamble: &str, acts: &[String], printed: &str) -> String {
    let mut page = format!(
        "---\ntitle: {name}\n---\n\n\
         <!-- Generated by `cargo xtask docs` from the test that measures this.\n     \
         Edit it there, not here. -->\n\n"
    );

    if !preamble.is_empty() {
        page.push_str(preamble);
        page.push_str("\n\n");
    }

    page.push_str("## What was done\n\n");
    for act in acts {
        page.push_str("```rust\n");
        page.push_str(act);
        page.push_str("\n```\n\n");
    }

    if !printed.is_empty() {
        page.push_str("## What the run printed\n\n");
        page.push_str(printed);
        page.push('\n');
    }

    page
}

fn tags(preamble: &str) -> Vec<String> {
    declared(preamble, "Tags:")
}

fn features(preamble: &str) -> Vec<String> {
    declared(preamble, "Features:")
}

fn declared(preamble: &str, field: &str) -> Vec<String> {
    preamble
        .lines()
        .find_map(|line| line.trim().strip_prefix(field))
        .into_iter()
        .flat_map(|list| list.split(','))
        .map(str::trim)
        .filter(|item| !item.is_empty())
        .map(str::to_string)
        .collect()
}

/// What the test printed, with cargo's own framing taken out.
///
/// The page is only true if the run happened, so this runs it rather than
/// reading the source and believing it. One thread, so what several tests
/// print stays in the order the file declares them.
fn output(
    stem: &str,
    features: &[String],
    shown: &BTreeMap<String, String>,
) -> Result<String, String> {
    let cleaned = ran(stem, features)?;
    let measured = measured_in(&cleaned)?;

    if !measured.is_empty() {
        for name in shown.keys() {
            let measured_it = measured
                .iter()
                .any(|record| record.get(name.as_str()).is_some());

            if !measured_it {
                return Err(format!(
                    "`//@show {name}` marks code no record reports:\n  \
                     the run printed no field by that name, so nothing would go under it"
                ));
            }
        }

        return Ok(laid_out(&measured, shown));
    }

    Ok(cleaned.join("\n").trim().to_string())
}

/// Runs one probe and hands back what it printed, with cargo's framing gone.
fn ran(stem: &str, features: &[String]) -> Result<Vec<String>, String> {
    let mut cargo = Command::new("cargo");
    cargo.args(["test", "-p", "amethystate", "--test", stem]);

    if !features.is_empty() {
        cargo.arg("--no-default-features");
        cargo.arg("--features");
        cargo.arg(features.join(","));
    }

    cargo.args(["--", "--nocapture", "--test-threads=1"]);

    let run = cargo
        .output()
        .map_err(|e| format!("could not start cargo: {e}"))?;

    if !run.status.success() {
        return Err(format!(
            "the test failed, so its output is not a finding:\n{}",
            String::from_utf8_lossy(&run.stderr)
        ));
    }

    Ok(String::from_utf8_lossy(&run.stdout)
        .lines()
        .filter_map(without_framing)
        .collect())
}

fn measured_in(cleaned: &[String]) -> Result<Vec<Value>, String> {
    cleaned
        .iter()
        .filter_map(|line| line.trim().strip_prefix("@measured "))
        .map(serde_json::from_str::<Value>)
        .collect::<Result<_, _>>()
        .map_err(|e| format!("a `@measured` line is not the record it claims to be: {e}"))
}

/// How the records are shown, decided here rather than in the probe.
///
/// A field carrying a document gets a fenced block under the code that made
/// it; a short one is a line beside its record. The first field names the
/// record, and `lang` is a fact about the text rather than a field of its own,
/// so it tags the fence and is not shown.
fn laid_out(measured: &[Value], shown: &BTreeMap<String, String>) -> String {
    const CELL: usize = 24;

    let mut columns: Vec<String> = Vec::new();
    for record in measured {
        for name in record.as_object().into_iter().flat_map(|it| it.keys()) {
            if name != "lang" && !columns.contains(name) {
                columns.push(name.clone());
            }
        }
    }

    let widest = |name: &str| {
        measured
            .iter()
            .filter_map(|record| record.get(name))
            .filter_map(Value::as_str)
            .map(|value| value.chars().count())
            .max()
            .unwrap_or(0)
    };

    let identity = columns.first().cloned().unwrap_or_default();

    let (narrow, wide): (Vec<&String>, Vec<&String>) = columns
        .iter()
        .filter(|name| **name != identity)
        .partition(|name| widest(name) <= CELL);

    let mut page = String::new();

    for record in measured {
        let named = columns
            .first()
            .and_then(|name| record.get(name.as_str()))
            .and_then(Value::as_str)
            .unwrap_or_default();
        let lang = record
            .get("lang")
            .and_then(Value::as_str)
            .unwrap_or_default();

        for name in &wide {
            let Some(body) = record.get(name.as_str()).and_then(Value::as_str) else {
                continue;
            };

            page.push_str(&format!("\n#### {named} - {name}\n\n"));

            if let Some(code) = shown.get(name.as_str()) {
                page.push_str(&format!("```rust\n{code}\n```\n\n"));
            }

            page.push_str(&format!("```{lang}\n{}\n```\n", body.trim_end()));
        }

        for name in &narrow {
            let value = cell(record, name);
            if !value.is_empty() {
                page.push_str(&format!("\n`{name}` reads back {value}.\n"));
            }
        }
    }

    page.trim().to_string()
}

fn cell(record: &Value, name: &str) -> String {
    match record.get(name).and_then(Value::as_str) {
        Some("") => "*empty*".to_string(),
        Some(value) => format!("`{value}`"),
        None => String::new(),
    }
}

/// `--nocapture` runs a test's own output together with the harness's: the
/// `test <name> ... ` header has no newline after it, so the first printed line
/// arrives glued to it, and the verdict lands alone at the end.
fn without_framing(line: &str) -> Option<String> {
    let line = line.trim_end();

    let header = line
        .strip_prefix("test ")
        .and_then(|rest| rest.find(" ... ").map(|at| &rest[at + " ... ".len()..]));

    let content = header.unwrap_or(line);
    let bare = content.trim();

    if header.is_some() && bare.is_empty() {
        return None;
    }

    if bare == "ok"
        || bare == "FAILED"
        || bare.starts_with("running ")
        || bare.starts_with("test result:")
    {
        return None;
    }

    Some(content.to_string())
}

fn acts(source: &str) -> Vec<String> {
    let mut found = Vec::new();
    let mut taking: Option<Vec<&str>> = None;

    for line in source.lines() {
        match line.trim() {
            "//@act" => taking = Some(Vec::new()),
            "//@end" => {
                if let Some(lines) = taking.take() {
                    let act = dedent(&lines);
                    if !act.is_empty() {
                        found.push(act);
                    }
                }
            }
            marker if marker.starts_with("//@show") || marker == "//@show-end" => {}
            _ => {
                if let Some(lines) = taking.as_mut() {
                    lines.push(line);
                }
            }
        }
    }

    found
}

/// What each `//@show <name>` names: the statements under it, up to the blank
/// line that ends them.
///
/// The heading of a block is then the code that produced it, taken from the
/// file rather than written out beside it, so the two cannot drift apart.
fn shown(source: &str) -> BTreeMap<String, String> {
    let mut found = BTreeMap::new();
    let mut taking: Option<(String, Vec<&str>)> = None;

    for line in source.lines() {
        let trimmed = line.trim();

        if trimmed == "//@show-end" {
            if let Some((name, lines)) = taking.take() {
                found.insert(name, dedent(&lines));
            }
            continue;
        }

        if let Some(name) = trimmed.strip_prefix("//@show") {
            if let Some((name, lines)) = taking.take() {
                found.insert(name, dedent(&lines));
            }
            taking = Some((name.trim().to_string(), Vec::new()));
            continue;
        }

        let Some((_, lines)) = taking.as_mut() else {
            continue;
        };

        lines.push(line);
    }

    if let Some((name, lines)) = taking {
        found.insert(name, dedent(&lines));
    }

    found
}

fn dedent(lines: &[&str]) -> String {
    let margin = lines
        .iter()
        .filter(|line| !line.trim().is_empty())
        .map(|line| line.len() - line.trim_start().len())
        .min()
        .unwrap_or(0);

    lines
        .iter()
        .map(|line| {
            if line.len() >= margin {
                &line[margin..]
            } else {
                line
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
        .trim_end()
        .to_string()
}

fn preamble(source: &str) -> String {
    source
        .lines()
        .skip_while(|line| {
            let line = line.trim();
            line.is_empty() || line.starts_with("#![")
        })
        .take_while(|line| line.trim_start().starts_with("//!"))
        .map(|line| line.trim_start().trim_start_matches("//!").trim_start())
        .collect::<Vec<_>>()
        .join("\n")
        .trim()
        .to_string()
}

/// What is in the section that no probe writes, so it can go.
///
/// The section's own index is the exception and the only page here written by
/// hand: it says what the section is for, which is not a thing any single run
/// can measure.
fn stale_pages(section: &Path, pages: &BTreeMap<PathBuf, String>) -> Vec<PathBuf> {
    let Ok(entries) = fs::read_dir(section) else {
        return Vec::new();
    };

    entries
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "md"))
        .filter(|path| path.file_name().is_none_or(|name| name != INDEX))
        .filter(|path| !pages.contains_key(path))
        .collect()
}

fn title(probe: &Path) -> String {
    probe
        .file_stem()
        .and_then(|stem| stem.to_str())
        .unwrap_or("unknown")
        .trim_start_matches("probe_")
        .replace('_', " ")
}

const BOOK: &str = "landing/src/content/docs";

/// Fills the book's code blocks from the tests that run them.
///
/// A page stays hand-written prose and asks for code by name:
///
/// ```md
/// <!-- shown: a store over a file -->
/// <!-- /shown -->
/// ```
///
/// What lands between the two is the region a test marks `//@show a store over
/// a file`, so what the book prints is what a run executes. Editing the block
/// on the page is pointless - the next run replaces it - and that is the
/// point: prose cannot drift from code it does not own.
///
/// A page can ask for what a run printed as well as what it ran:
///
/// ```md
/// <!-- printed: a path past the cap from book_errors -->
/// <!-- /printed -->
/// ```
///
/// which is filled with the `a path past the cap` field of a `measured` record
/// that `tests/book_errors.rs` prints. The test is named because only the named
/// ones run, so a book with no such request still costs nothing to fill.
///
/// Anything varying between runs - a temporary path, a duration, a process id -
/// makes the page churn, so keep it out of the field rather than out of the
/// page.
fn book() -> ExitCode {
    let pages = markdown_under(Path::new(BOOK));
    if pages.is_empty() {
        eprintln!("no pages under {BOOK} - run this from the workspace root");
        return ExitCode::FAILURE;
    }

    let Some(version) = declared_version() else {
        eprintln!("cannot read the workspace version out of Cargo.toml");
        return ExitCode::FAILURE;
    };

    let mut regions: BTreeMap<String, String> = BTreeMap::new();
    for probe in probe_files(Path::new(PROBES)) {
        let Ok(source) = fs::read_to_string(&probe) else {
            continue;
        };
        regions.extend(shown(&source));
    }

    let mut wanted: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for page in &pages {
        let Ok(source) = fs::read_to_string(page) else {
            continue;
        };
        for (field, stem) in asked_to_print(&source) {
            wanted.entry(stem).or_default().push(field);
        }
    }

    let printed = match run_for(&wanted) {
        Ok(printed) => printed,
        Err(why) => {
            eprintln!("{why}");
            return ExitCode::FAILURE;
        }
    };

    let declared = methods_by_type(Path::new("crates"));
    let crates = crate_names(Path::new("crates"));

    let mut filled = 0;
    let mut behind: Vec<String> = Vec::new();
    let mut missing: Vec<String> = Vec::new();
    let mut unprinted: Vec<String> = Vec::new();
    let mut renamed: Vec<String> = Vec::new();

    for page in &pages {
        let Ok(source) = fs::read_to_string(page) else {
            continue;
        };

        let done = fill(&source, &regions, &printed, &version);

        for name in unknown_names(&done.page, &declared, &crates) {
            renamed.push(format!("{}: `{name}`", page.display()));
        }
        for name in done.no_test_marks {
            missing.push(format!("{}: {name}", page.display()));
        }
        for name in done.no_run_prints {
            unprinted.push(format!("{}: {name}", page.display()));
        }

        filled += done.asked;

        if done.page != source {
            behind.push(page.display().to_string());
            if !std::env::args().any(|arg| arg == "--check")
                && let Err(e) = fs::write(page, &done.page)
            {
                eprintln!("cannot write {}: {e}", page.display());
                return ExitCode::FAILURE;
            }
        }
    }

    if !missing.is_empty() {
        eprintln!("a page asks for code no test marks:");
        for at in &missing {
            eprintln!("  {at}");
        }
        eprintln!("\nmark it in a test with `//@show <name>`, or drop the request");
        return ExitCode::FAILURE;
    }

    if !unprinted.is_empty() {
        eprintln!("a page asks for output no run produced:");
        for at in &unprinted {
            eprintln!("  {at}");
        }
        eprintln!("\nname the field in the test's `measured` record, or drop the request");
        return ExitCode::FAILURE;
    }

    if !renamed.is_empty() {
        eprintln!("a page says a type has something it does not:");
        for at in &renamed {
            eprintln!("  {at}");
        }
        eprintln!(
            "\nthe code blocks come from tests and cannot say this - it is the prose \
             around them. Write `Type::member` there and this is checked; write the \
             member on its own and nothing is."
        );
        return ExitCode::FAILURE;
    }

    if behind.is_empty() {
        println!("{filled} block(s) in {BOOK} are what their tests run");
        return ExitCode::SUCCESS;
    }

    if std::env::args().any(|arg| arg == "--check") {
        eprintln!("out of date, run `cargo xtask book`:");
        for at in &behind {
            eprintln!("  {at}");
        }
        return ExitCode::FAILURE;
    }

    println!(
        "filled {filled} block(s), {} page(s) rewritten",
        behind.len()
    );
    ExitCode::SUCCESS
}


/// What each type in the workspace has on it, read out of the syntax rather
/// than looked for in the text.
///
/// Every `impl` contributes to the type it is for, its trait impls included,
/// because a reader calling `store.close()` does not care which block it was
/// written in.
fn methods_by_type(at: &Path) -> BTreeMap<String, BTreeSet<String>> {
    let mut found = BTreeMap::new();
    collect_methods(at, &mut found);
    found
}

fn collect_methods(at: &Path, into: &mut BTreeMap<String, BTreeSet<String>>) {
    let Ok(entries) = fs::read_dir(at) else {
        return;
    };

    for entry in entries.filter_map(Result::ok) {
        let path = entry.path();
        if path.is_dir() {
            if path
                .file_name()
                .is_some_and(|n| n == "target" || n == "node_modules")
            {
                continue;
            }
            collect_methods(&path, into);
            continue;
        }
        if path.extension().is_none_or(|ext| ext != "rs") {
            continue;
        }
        let Ok(source) = fs::read_to_string(&path) else {
            continue;
        };
        let Ok(file) = syn::parse_file(&source) else {
            continue;
        };

        for item in &file.items {
            gather(item, into);
        }
    }
}

fn gather(item: &syn::Item, into: &mut BTreeMap<String, BTreeSet<String>>) {
    match item {
        syn::Item::Mod(m) => {
            if let Some((_, items)) = &m.content {
                for inner in items {
                    gather(inner, into);
                }
            }
        }
        syn::Item::Impl(block) => {
            let Some(name) = named(&block.self_ty) else {
                return;
            };
            let on = into.entry(name).or_default();
            for member in &block.items {
                if let syn::ImplItem::Fn(f) = member {
                    on.insert(f.sig.ident.to_string());
                }
            }
        }
        syn::Item::Trait(t) => {
            let on = into.entry(t.ident.to_string()).or_default();
            for member in &t.items {
                if let syn::TraitItem::Fn(f) = member {
                    on.insert(f.sig.ident.to_string());
                }
            }
        }
        syn::Item::Struct(s) => {
            let on = into.entry(s.ident.to_string()).or_default();
            for field in &s.fields {
                if let Some(name) = &field.ident {
                    on.insert(name.to_string());
                }
            }
        }
        syn::Item::Enum(e) => {
            let on = into.entry(e.ident.to_string()).or_default();
            for variant in &e.variants {
                on.insert(variant.ident.to_string());
            }
        }
        _ => {}
    }
}

/// The bare name of a type, with any reference, generic or path stripped off.
fn named(ty: &syn::Type) -> Option<String> {
    match ty {
        syn::Type::Path(p) => p.path.segments.last().map(|s| s.ident.to_string()),
        syn::Type::Reference(r) => named(&r.elem),
        _ => None,
    }
}

/// What a page's prose claims a type has, that the type does not have.
///
/// Fenced blocks are skipped: they are filled from tests that compile, so they
/// cannot say a name the code does not have. Only the sentences around them
/// can, and `Type::method` in backticks is what makes those checkable - the
/// bare `method` was not, which is how `StoreBuilder::watch_debounce` outlived
/// the method by a rename.
fn unknown_names(
    page: &str,
    methods: &BTreeMap<String, BTreeSet<String>>,
    crates: &BTreeSet<String>,
) -> Vec<String> {
    let prose: String = page.split("```").step_by(2).collect::<Vec<_>>().join("\n");

    let mut wrong = Vec::new();
    let mut rest = prose.as_str();

    while let Some(open) = rest.find('`') {
        rest = &rest[open + 1..];
        let Some(close) = rest.find('`') else { break };
        let token = &rest[..close];
        rest = &rest[close + 1..];

        let path: Vec<&str> = token.split("::").collect();
        if path.len() < 2 || path.iter().any(|s| s.is_empty()) {
            continue;
        }
        if path
            .iter()
            .any(|s| s.contains(|c: char| !c.is_alphanumeric() && c != '_'))
        {
            continue;
        }

        let root = path[0];
        let ours = methods.contains_key(root) || crates.contains(root);
        if !ours {
            continue;
        }

        let last = path[path.len() - 1];
        let owner = path[path.len() - 2];

        // The owner decides what the last segment is, not its case: a variant
        // is a member spelled like a type, and both live on the type here.
        let complaint = match methods.get(owner) {
            Some(has) if !has.contains(last) => {
                Some(format!("{token} - `{owner}` has no `{last}`"))
            }
            Some(_) => None,
            None if last.starts_with(|c: char| c.is_uppercase()) => {
                (!methods.contains_key(last)).then(|| format!("{token} - no such type"))
            }
            // A path through modules to a module or a free function. Neither is
            // indexed, so there is nothing to check and nothing to claim.
            None => None,
        };

        if let Some(said) = complaint
            && !wrong.contains(&said)
        {
            wrong.push(said);
        }
    }

    wrong
}

/// What this workspace's crates are called, as a path in the book would spell
/// them: the directory name with its dashes turned into underscores.
///
/// A qualified name rooted here is ours and gets checked. One rooted anywhere
/// else - `std`, `serde_json`, `anyhow` - belongs to somebody whose source is
/// not in this tree, and guessing at it would only produce noise.
fn crate_names(at: &Path) -> BTreeSet<String> {
    let mut found = BTreeSet::new();
    let Ok(entries) = fs::read_dir(at) else {
        return found;
    };

    for entry in entries.filter_map(Result::ok) {
        let path = entry.path();
        if path.is_dir() {
            if path.join("Cargo.toml").is_file()
                && let Some(name) = path.file_name().and_then(|n| n.to_str())
            {
                found.insert(name.replace('-', "_"));
            }
            found.extend(crate_names(&path));
        }
    }

    found
}

fn markdown_under(at: &Path) -> Vec<PathBuf> {
    let Ok(entries) = fs::read_dir(at) else {
        return Vec::new();
    };

    let mut found = Vec::new();
    for entry in entries.filter_map(Result::ok) {
        let path = entry.path();
        if path.is_dir() {
            found.extend(markdown_under(&path));
        } else if path.extension().is_some_and(|ext| ext == "md") {
            found.push(path);
        }
    }

    found.sort();
    found
}

/// What the workspace says this crate's version is, as a dependency would
/// name it.
///
/// A version written into the book by hand is a version nobody updates on the
/// next bump, so the manifest says it and the book repeats it.
fn declared_version() -> Option<String> {
    let manifest = fs::read_to_string("Cargo.toml").ok()?;

    let full = manifest
        .lines()
        .skip_while(|line| line.trim() != "[workspace.package]")
        .find_map(|line| line.trim().strip_prefix("version = "))?
        .trim()
        .trim_matches('"');

    let mut parts = full.split('.');
    Some(format!("{}.{}", parts.next()?, parts.next()?))
}

/// Every line naming this crate as a dependency, carrying the version the
/// manifest declares rather than one somebody typed.
fn with_version(line: &str, version: &str) -> String {
    if !line.contains("amethystate") {
        return line.to_string();
    }

    let Some(at) = line
        .find("version = \"")
        .map(|at| at + "version = \"".len())
        .or_else(|| {
            line.find("amethystate = \"")
                .map(|at| at + "amethystate = \"".len())
        })
    else {
        return line.to_string();
    };

    let Some(end) = line[at..].find('"').map(|end| at + end) else {
        return line.to_string();
    };

    format!("{}{version}{}", &line[..at], &line[end..])
}

/// The page with every `<!-- shown: name -->` block replaced by what the test
/// marked, plus how many were asked for and which had nothing to fill them.
/// What a page asks a run to print into it, as `(field, test)` pairs.
fn asked_to_print(source: &str) -> Vec<(String, String)> {
    source
        .lines()
        .filter_map(|line| {
            line.trim()
                .strip_prefix("<!-- printed:")
                .and_then(|rest| rest.strip_suffix("-->"))
        })
        .filter_map(|rest| rest.trim().rsplit_once(" from "))
        .map(|(field, stem)| (field.trim().to_string(), stem.trim().to_string()))
        .collect()
}

/// One value a run printed, with the fence language it asked for.
type Printed = BTreeMap<(String, String), (String, String)>;

/// Runs each test a page named and keeps the fields those pages asked for.
///
/// Only the named tests run: a page that asks for nothing costs nothing, which
/// is what keeps filling the book cheap enough to do on every edit.
fn run_for(wanted: &BTreeMap<String, Vec<String>>) -> Result<Printed, String> {
    let mut printed = Printed::new();

    for (stem, fields) in wanted {
        let at = Path::new(PROBES).join(format!("{stem}.rs"));
        let source = fs::read_to_string(&at).map_err(|_| {
            format!("a page asks for output from `{stem}`, and there is no test by that name")
        })?;

        eprintln!("running {stem}");
        let cleaned = ran(stem, &features(&preamble(&source)))?;
        let measured = measured_in(&cleaned)?;

        for field in fields {
            let record = measured
                .iter()
                .find(|record| record.get(field.as_str()).is_some())
                .ok_or_else(|| format!("`{stem}` ran and printed no field named `{field}`"))?;

            let value = record
                .get(field.as_str())
                .and_then(Value::as_str)
                .ok_or_else(|| format!("`{stem}` prints `{field}`, but not as text"))?;

            let lang = record
                .get("lang")
                .and_then(Value::as_str)
                .unwrap_or_default();

            printed.insert(
                (stem.clone(), field.clone()),
                (value.to_string(), lang.to_string()),
            );
        }
    }

    Ok(printed)
}

struct Filled {
    page: String,
    asked: usize,
    no_test_marks: Vec<String>,
    no_run_prints: Vec<String>,
}

fn fill(
    source: &str,
    regions: &BTreeMap<String, String>,
    printed: &Printed,
    version: &str,
) -> Filled {
    let mut out: Vec<String> = Vec::new();
    let mut asked = 0;
    let mut no_test_marks = Vec::new();
    let mut no_run_prints = Vec::new();
    let mut closing: Option<&str> = None;

    for line in source.lines() {
        let trimmed = line.trim();

        if let Some(end) = closing {
            if trimmed == end {
                out.push(line.to_string());
                closing = None;
            }
            continue;
        }

        out.push(with_version(line, version));

        if let Some(name) = trimmed
            .strip_prefix("<!-- shown:")
            .and_then(|rest| rest.strip_suffix("-->"))
            .map(str::trim)
        {
            asked += 1;
            closing = Some("<!-- /shown -->");

            match regions.get(name) {
                Some(code) => {
                    out.push("```rust".to_string());
                    out.push(code.clone());
                    out.push("```".to_string());
                }
                None => no_test_marks.push(name.to_string()),
            }
            continue;
        }

        let Some(request) = trimmed
            .strip_prefix("<!-- printed:")
            .and_then(|rest| rest.strip_suffix("-->"))
            .map(str::trim)
        else {
            continue;
        };

        asked += 1;
        closing = Some("<!-- /printed -->");

        let Some((field, stem)) = request.rsplit_once(" from ") else {
            no_run_prints.push(format!("{request} (say which test: `<field> from <test>`)"));
            continue;
        };

        let key = (stem.trim().to_string(), field.trim().to_string());
        match printed.get(&key) {
            Some((value, lang)) => {
                out.push(format!("```{lang}"));
                out.push(value.clone());
                out.push("```".to_string());
            }
            None => no_run_prints.push(request.to_string()),
        }
    }

    let mut page = out.join("\n");
    if source.ends_with('\n') {
        page.push('\n');
    }

    Filled {
        page,
        asked,
        no_test_marks,
        no_run_prints,
    }
}
