[package]
name = "amethystate-slint-settings-example"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
amethystate = { path = "../../crates/main/amethystate", features = ["redb"] }
serde = { version = "1.0", features = ["derive"] }
slint = "1.16.1"

[build-dependencies]
slint-build = "1.16.1"
